# Site Config

name: AlexFlipnote
title: AlexFlipnote
twitter: AlexFlipnote

themecolour: "#2196F3"

domain: "https://alexflipnote.xyz"
baseurl: ""
url: "https://alexflipnote.xyz"
encoding: utf-8

include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed
